# Generated by Django 4.2.11 on 2024-05-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("task_id", models.IntegerField(primary_key=True, serialize=False)),
                ("task_desc", models.CharField(blank=True, max_length=50)),
                ("task_deadline", models.DateTimeField(null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField()),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Incomplete"), (1, "Completed")]),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("study", "Study"),
                            ("fitness", "Fitness"),
                            ("errands", "Errands"),
                            ("mental_health", "Mental Health"),
                            ("academic", "Academic"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.user"
                    ),
                ),
            ],
        ),
    ]
