# Generated by Django 4.2.11 on 2024-05-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_todo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="last_edited",
            field=models.DateTimeField(null=True),
        ),
    ]
