# Generated by Django 4.2.11 on 2024-05-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_todo_last_edited"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                ("subtask_id", models.AutoField(primary_key=True, serialize=False)),
                ("subtask_desc", models.CharField(max_length=25)),
                ("parent_id", models.IntegerField(null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.todo"
                    ),
                ),
            ],
        ),
    ]
