# Generated by Django 4.2.11 on 2024-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_subtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="subtask_desc",
            field=models.CharField(max_length=45),
        ),
    ]
