# Generated by Django 4.2.11 on 2024-05-02 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_todo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="subtask_desc",
            field=models.CharField(
                max_length=65,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=30),
        ),
    ]
