# Generated by Django 4.2.11 on 2024-05-03 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_subtask_status_alter_subtask_subtask_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="task_desc",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
