# Generated by Django 4.2.11 on 2024-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_alter_todo_status_alter_todo_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Incomplete"), (1, "Completed")], default=0
            ),
        ),
    ]
