# Generated by Django 4.2.11 on 2024-05-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
