# Generated by Django 4.2.11 on 2024-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_alter_todo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
