# Generated by Django 4.2.11 on 2024-05-06 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_alter_todo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="p@ssw0rd123",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
